=== 20203tn097/Sentinel-Azure/.script/utils/schemas/fluentbit_CL (Azure Cloud NGFW by PaloAlto)_ConnectorSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "publisher": {
      "type": "string"
    },
    "descriptionMarkdown": {
      "type": "string"
    },
    "graphQueries": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "metricName": {
              "type": "string"
            },
            "legend": {
              "type": "string"
            },
            "baseQuery": {
              "type": "string"
            }
          },
          "required": [
            "metricName",
            "legend",
            "baseQuery"
          ]
        }
      ]
    },
    "sampleQueries": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        }
      ]
    },
    "connectivityCriterias": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "value": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "type",
            "value"
          ]
        }
      ]
    },
    "dataTypes": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        }
      ]
    },
    "availability": {
      "type": "object",
      "properties": {
        "status": {
          "type": "integer"
        },
        "isPreview": {
          "type": "boolean"
        }
      },
      "required": [
        "status",
        "isPreview"
      ]
    },
    "permissions": {
      "type": "object",
      "properties": {
        "resourceProvider": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "provider": {
                  "type": "string"
                },
                "permissionsDisplayText": {
                  "type": "string"
                },
                "providerDisplayName": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "requiredPermissions": {
                  "type": "object",
                  "properties": {
                    "read": {
                      "type": "boolean"
                    },
                    "write": {
                      "type": "boolean"
                    },
                    "delete": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "read",
                    "write",
                    "delete"
                  ]
                }
              },
              "required": [
                "provider",
                "permissionsDisplayText",
                "providerDisplayName",
                "scope",
                "requiredPermissions"
              ]
            },
            {
              "type": "object",
              "properties": {
                "provider": {
                  "type": "string"
                },
                "permissionsDisplayText": {
                  "type": "string"
                },
                "providerDisplayName": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "requiredPermissions": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "action"
                  ]
                }
              },
              "required": [
                "provider",
                "permissionsDisplayText",
                "providerDisplayName",
                "scope",
                "requiredPermissions"
              ]
            }
          ]
        }
      },
      "required": [
        "resourceProvider"
      ]
    },
    "instructionSteps": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "instructions": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "parameters": {
                      "type": "object",
                      "properties": {
                        "linkType": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "linkType"
                      ]
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "parameters",
                    "type"
                  ]
                }
              ]
            }
          },
          "required": [
            "title",
            "description",
            "instructions"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        }
      ]
    },
    "metadata": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "source": {
          "type": "object",
          "properties": {
            "kind": {
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "author": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        },
        "support": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "link": {
              "type": "string"
            },
            "tier": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "link",
            "tier"
          ]
        }
      },
      "required": [
        "id",
        "version",
        "kind",
        "source",
        "author",
        "support"
      ]
    }
  },
  "required": [
    "id",
    "title",
    "publisher",
    "descriptionMarkdown",
    "graphQueries",
    "sampleQueries",
    "connectivityCriterias",
    "dataTypes",
    "availability",
    "permissions",
    "instructionSteps",
    "metadata"
  ]
}

=== 20203tn097/Sentinel-Azure/Solutions/Sensor SSH Cowrie/Data Connectors/Cowrie_ARM_Deployment.json
{
    "id": "SensorSSHCowrie",
    "title": "Sensor SSH Cowrie",
    "publisher": "Microsoft",
    "descriptionMarkdown": "The Sensor SSH Cowrie data connector provides the capability to deploy a Linux based Azure VM host with Cowrie setup and configured. Included with CustomTable, AMA, DCR, DCE ready to go and ingesting Cowrie events on host. You can deploy this as a internal / private sensor (HoneyPot) on your existing virtual netwrk and subnet acting as a tripwire and can use the detection rules. Alternatively you can deploy sensor (HoneyPot) publically on the Internet and collect threat inetellegnce. This connector provides Microsoft Sentinel the capability to view dashboards, create custom alerts, collect Threat Intellegence",
    "graphQueries": [
        {
            "metricName": "Total data received",
            "legend": "newCowrie_CL",
            "baseQuery": "newCowrie_CL"
        },
        {
            "metricName": "Total data received",
            "legend": "newCowrie_CL",
            "baseQuery": "newCowrie_CL"
        }
    ],
    "sampleQueries": [
		{
            "description" : "Top 10 Cowrie Events detected",
            "query": "newCowrie_CL\n | extend Message = tostring(parse_json(RawData).message)\n | summarize count() by Message\n | top 10 by count_"
        }
     ],
    "dataTypes": [
        {
            "name": "newCowrie_CL",
            "lastDataReceivedQuery": "newCowrie_CL\n            | summarize Time = max(TimeGenerated)\n            | where isnotempty(Time)"          
        },
		{
            "name": "newCowrie_CL",
            "lastDataReceivedQuery": "newCowrie_CL\n            | summarize Time = max(TimeGenerated)\n            | where isnotempty(Time)"
        }
    ],
    "connectivityCriterias": [
        {
            "type": "IsConnectedQuery",
            "value": [
                "newCowrie_CL\n            | summarize LastLogReceived = max(TimeGenerated)\n            | project IsConnected = LastLogReceived > ago(30d)",
                "newCowrie_CL\n            | summarize LastLogReceived = max(TimeGenerated)\n            | project IsConnected = LastLogReceived > ago(30d)"

            ]
        }
    ],
    "availability": {
        "status": 1,
        "isPreview": false
    },
    "permissions": {
        "resourceProvider": [
            {
                "provider": "Microsoft.OperationalInsights/workspaces",
                "permissionsDisplayText": "read and write permissions on the workspace are required.",
                "providerDisplayName": "Workspace",
                "scope": "Workspace",
                "requiredPermissions": {
                    "write": true,
                    "read": true,
                    "delete": true
                }
            },
			{
				"provider": "Microsoft.OperationalInsights/workspaces/sharedKeys",
				"permissionsDisplayText": "read permissions to shared keys for the workspace are required. [See the documentation to learn more about workspace keys](https://docs.microsoft.com/azure/azure-monitor/platform/agent-windows#obtain-workspace-id-and-key).",
				"providerDisplayName": "Keys",
				"scope": "Workspace",
				"requiredPermissions": {
					"action": true
				}
			}
        ],
        "customs": [
            {
                "name": "Contributor Role",
                "description": "Contributor role permissions to deploy a Azure VM, add a Custom Table to Log Analytics, DCR, DCE, AMA."
            }
        ]
    },
    "instructionSteps": [
        {
            "title": "",
            "description": ">**NOTE:** This connector deploys a Debian Azure VM, Cowrie software, CustomTable, AMA, DCR, DCE, uses AMA to pull Cowrie JSON logs into Microsoft Sentinel. This might result in additional data ingestion costs."
        },
        {
            "title": "Option 1 - Private - Azure Resource Manager (ARM) Template",
            "description": "Use this method for automated deployment of the Cowrie VM using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](https://aka.ms/deploytoazurebutton)](https://aka.ms/sentinel-cowrie-azuredeployprivate)\n2. Mark the checkbox labeled **I agree to the terms and conditions stated above**. \n3. Click **Purchase** to deploy."
        },
        {
            "title": "Option 2 - Public - Azure Resource Manager (ARM) Template",
            "description": "Use this method for automated deployment of the Cowrie VM using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](https://aka.ms/deploytoazurebutton)](https://aka.ms/sentinel-cowrie-azuredeploypublic)\n2. Mark the checkbox labeled **I agree to the terms and conditions stated above**. \n3. Click **Purchase** to deploy."
        },
        {
            "title": "",
            "description": "**Post Deployment**\n\n1.  From the Azure Portal, navigate to the data collection rule cowrie-dcr, click on resources, you will see your VM with a data collection rule associated, Next you must associate Data Collection Endpoint (DCE) cowrie-dce and press Save."
        }
    ],
    "metadata": {
        "id": "d4a44059-a0d1-4e76-a8c5-535d381c0872",
        "version": "2.0.0",
        "kind": "dataConnector",
        "source": {
          "kind": "Solution"
        },
        "author": {
          "name": "Microsoft"
        },
        "support": {
            "name": "Microsoft Corporation",
            "email": "support@microsoft.com",
            "tier": "Microsoft",
            "link": "https://support.microsoft.com"
        }
      }
}
